In [2]:
# RUN THIS CELL FIRST TO IMPORT ALL NECESSARY LIBRARIES
import pandas as pd
import numpy as np
import requests
import time
import io
import os

### EXTRACT DATA

In [ ]:
# RUN THIS CELL ONLY TO UPDATE THE ISTAT DATA
# this cell save the istat data in a raw data folder in order to avoid running the api call every time
url = "https://esploradati.istat.it/SDMXWS/rest/data/41_983"
header = {"Accept":"application/vnd.sdmx.data+csv;version=1.0.0"}
response = requests.get(url, headers=header)
print(response.status_code)

with open("data/raw/istat_incidenti.csv", "w", encoding="utf-8") as f:
    f.write(response.text)

200

In [30]:
# RUN THIS CELL ONCE TO DOWNLOAD SITUAS DATA
# this cell save the situas data from 31-12-2001 to 31-12-2024 in 24 different csv files
date_ranges = [f"{year}-12-31" for year in range(2001, 2025)]

# to download files in csv format is necessary to set json and header parameters.
# You can acknowledge this by using dev tools on the web page at the below specified url.
json_situas = {"orderFields":[],"orderDirects":[],"pFilterFields":[],"pFilterValues":[]}
header_situas = {"Content-Type": "application/json-patch+json"}

for i in date_ranges:
    url_situas = f"https://situas.istat.it/ShibO2Module/api/Report/Spool/{i}/74?&pdoctype=CSV"
    time.sleep(1)
    response_situas = requests.post(url_situas, json = json_situas, headers = header_situas)
    print(response_situas.status_code)
    if response_situas.status_code == 200:
        with open(f"data/raw/situas_{i[0:4]}.csv", "w", encoding="utf-8") as f:
            f.write(response_situas.text)
    else:
        # if an http status code different from 200 is encounterd, this make sure that cell execution is stopped
        raise SystemExit(f"Abort due to http error {response_situas.status_code}")
print(f"All done - {len(date_ranges)} files downloaded")

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
All done - 24 files downloaded

### CLEAN DATA

We begin cleaning data with `SITUAS data` csv file

In [3]:
situas_df = pd.read_csv("data/raw/situas_2001.csv", sep = ";", decimal = ",")
situas_df["Anno"] = 2001
print(f"Year 2001:{situas_df.shape}")
situas_df = [situas_df]

for i in range(2002,2025):
    tmp_df = pd.read_csv(f"data/raw/situas_{i}.csv", sep = ";", decimal = ",")
    tmp_df["Anno"] = i # add a column with the year of the data

# Analyzing the csv situas data, it can be noticed that from 2015 on there is another column 
# not present in the previous years "Codice Provincia (Storico)"". This is simply the code that 
# in the previous years is called "Codice Provincia/Uts" which from 2015 on contains different values. 
# So, we can drop "Codice Provincia/Uts" and change "Codice Provincia (Storico)"" name in "Codice Provincia/Uts"
# in order to obtain a uniform dataframe.
    if i in range(2015,2025):
        tmp_df.drop(columns=["Codice Provincia/Uts"], inplace = True)
        tmp_df.rename(columns={"Codice Provincia (Storico)": "Codice Provincia/Uts"}, inplace = True)

    # check if columns name are the same among csv files in both directions
    check_column_names_sx = set(situas_df[0].columns) - set(tmp_df.columns)
    check_column_names_dx = set(tmp_df.columns) - set(situas_df[0].columns)

    # check if columns order are the same among csv files
    check_column_order = list(situas_df[0].columns) == list(tmp_df.columns)

    if len(check_column_names_sx) == 0 and len(check_column_names_dx) == 0 and check_column_order:
        print(f"Year {i}: {tmp_df.shape}")
        situas_df.append(tmp_df)
    else:
        print(situas_df[0].columns)
        print(tmp_df.columns)
        raise SystemExit(f"Abort due to column name mismatch in situas_{i}.csv")
situas_df = pd.concat(situas_df, ignore_index = True)

Year 2001:(8102, 17)
Year 2002: (8102, 17)
Year 2003: (8100, 17)
Year 2004: (8101, 17)
Year 2005: (8101, 17)
Year 2006: (8101, 17)
Year 2007: (8101, 17)
Year 2008: (8101, 17)
Year 2009: (8100, 17)
Year 2010: (8094, 17)
Year 2011: (8092, 17)
Year 2012: (8092, 17)
Year 2013: (8090, 17)
Year 2014: (8057, 17)
Year 2015: (8046, 17)
Year 2016: (7998, 17)
Year 2017: (7978, 17)
Year 2018: (7954, 17)
Year 2019: (7914, 17)
Year 2020: (7903, 17)
Year 2021: (7904, 17)
Year 2022: (7904, 17)
Year 2023: (7900, 17)
Year 2024: (7896, 17)

From the shapes of the previous cell, we can notice that the number of rows change for every situas csv file. Since that every record in these csv files is a different town, this means that the number of town changes every year. This happens because some towns splits or merge toghether with others. This kind of town usually are very small so it's difficult that they could be interesting for investment from business. So we can simply keep just the towns that are present in every csv file. In order to confirm this strategy, we can calculate how many towns are in common between all csv files.

In [4]:
# Determine the total number of distinct years covered by the dataset.
tot_years = situas_df["Anno"].nunique()

# Count the number of years in which each municipality appears.
count_years_per_town = situas_df.groupby("Codice Comune (alfanumerico)")["Anno"].nunique()

# Select towns that are present in all years of the dataset.
towns_common_code = count_years_per_town[count_years_per_town == tot_years].index
print(len(towns_common_code))

7488

Since that the majority of towns don't change through years, we can assess that the bigger towns are not excluded from the analysis and we can confirm the strategy. We drop changing towns because to do a correct analysis, we have to work on towns that have the same amount of data

In [5]:
# Keep only towns that are present in every year of the dataset,
# then reset the DataFrame index after filtering.
situas_df = situas_df[
    situas_df['Codice Comune (alfanumerico)'].isin(towns_common_code)
]
situas_df.reset_index(inplace=True, drop=True)
print(situas_df.info())
situas_df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 179712 entries, 0 to 179711
Data columns (total 17 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ï»¿Codice Ripartizione geografica  179712 non-null  int64
 1   Codice Regione                     179712 non-null  int64
 2   Codice Provincia/Uts               179712 non-null  int64
 3   Codice Comune (alfanumerico)       179712 non-null  int64
 4   Codice Comune (numerico)           179712 non-null  int64
 5   Comune                             179688 non-null  str
 6   Comune (dizione straniera)         2904 non-null    str
 7   Sigla automobilistica              177504 non-null  str
 8   Capoluogo di Provincia/Uts         179712 non-null  int64
 9   Capoluogo di Regione               179712 non-null  int64
 10  Popolazione legale                 179712 non-null  float64
 11  Anno Censimento                    179712 non-null  int64
 12  Superficie (Kmq)                   179712 non-null  str
 13  Anno (Superficie)                  179712 non-null  int64
 14  Popolazione residente              179712 non-null  int64
 15  Anno (Popolazione residente)       179712 non-null  int64
 16  Anno                               179712 non-null  int64
dtypes: float64(1), int64(12), str(4)
memory usage: 23.3 MB
None

,ï»¿Codice Ripartizione geografica,Codice Regione,Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente),Anno
0,1,1,1,1001,1001,AgliÃ¨,NaN,TO,0,0,2574.0,2001,"13,1462",2001,2557,2001,2001
1,1,1,1,1002,1002,Airasca,NaN,TO,0,0,3554.0,2001,"15,7393",2001,3543,2001,2001
2,1,1,1,1003,1003,Ala di Stura,NaN,TO,0,0,479.0,2001,"46,3315",2001,480,2001,2001
3,1,1,1,1004,1004,Albiano d'Ivrea,NaN,TO,0,0,1696.0,2001,"11,7315",2001,1687,2001,2001
4,1,1,1,1006,1006,Almese,NaN,TO,0,0,5658.0,2001,"17,8756",2001,5648,2001,2001
5,1,1,1,1007,1007,Alpette,NaN,TO,0,0,300.0,2001,"5,6261",2001,293,2001,2001
6,1,1,1,1008,1008,Alpignano,NaN,TO,0,0,16648.0,2001,"11,9193",2001,16647,2001,2001
7,1,1,1,1009,1009,Andezeno,NaN,TO,0,0,1705.0,2001,"7,4861",2001,1712,2001,2001
8,1,1,1,1010,1010,Andrate,NaN,TO,0,0,476.0,2001,"9,3085",2001,474,2001,2001
9,1,1,1,1011,1011,Angrogna,NaN,TO,0,0,777.0,2001,"38,8782",2001,777,2001,2001

In [6]:
# drop the column "Comune (dizione straniera) since that have a lot nan values and is not useful for our analysis"
situas_df.drop(columns=['Comune (dizione straniera)'],inplace=True)

In [7]:
# Loading the situas data, it can be noticed that the first column name is not correct. 
# It is called "ï»¿Codice Ripartizione geografica" instead of "Codice Ripartizione geografica". 
# This is due to a problem with the encoding of the csv file. We can fix this by renaming the column.
situas_df.rename(columns={'ï»¿Codice Ripartizione geografica': 'Codice Ripartizione geografica'}, inplace=True)
print(situas_df.info())
print(situas_df.sample(10))

<class 'pandas.DataFrame'>
RangeIndex: 179712 entries, 0 to 179711
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Codice Ripartizione geografica  179712 non-null  int64
 1   Codice Regione                  179712 non-null  int64
 2   Codice Provincia/Uts            179712 non-null  int64
 3   Codice Comune (alfanumerico)    179712 non-null  int64
 4   Codice Comune (numerico)        179712 non-null  int64
 5   Comune                          179688 non-null  str
 6   Sigla automobilistica           177504 non-null  str
 7   Capoluogo di Provincia/Uts      179712 non-null  int64
 8   Capoluogo di Regione            179712 non-null  int64
 9   Popolazione legale              179712 non-null  float64
 10  Anno Censimento                 179712 non-null  int64
 11  Superficie (Kmq)                179712 non-null  str
 12  Anno (Superficie)               179712 non-null  int64
 13  Popolazione residente           179712 non-null  int64
 14  Anno (Popolazione residente)    179712 non-null  int64
 15  Anno                            179712 non-null  int64
dtypes: float64(1), int64(12), str(3)
memory usage: 21.9 MB
None
        Codice Ripartizione geografica  Codice Regione  Codice Provincia/Uts  \
178430                               4              18                    78
147657                               4              13                    66
14971                                1               1                   103
88639                                4              18                    79
77582                                2               4                    21
119129                               5              20                    90
54002                                1               3                    13
110762                               4              16                    75
57476                                4              15                    64
173194                               1               1                     6

        Codice Comune (alfanumerico)  Codice Comune (numerico)  \
178430                         78134                     78134
147657                         66075                     66075
14971                         103072                    103072
88639                          79088                     79088
77582                          21097                     21097
119129                         90025                     90025
54002                          13222                     13222
110762                         75082                     75082
57476                          64025                     64025
173194                          6139                      6139

                           Comune Sigla automobilistica  \
178430  Santo Stefano di Rogliano                    CS
147657            Pratola Peligna                    AQ
14971                    Verbania                    VB
88639                     Olivadi                    CZ
77582              Terlano/Terlan                    BZ
119129                Chiaramonti                    SS
54002                  Tavernerio                    CO
110762                     Surano                    LE
57476                   Cervinara                    AV
173194                     Prasco                    AL

        Capoluogo di Provincia/Uts  Capoluogo di Regione  Popolazione legale  \
178430                           0                     0              1704.0
147657                           0                     0              7840.0
14971                            1                     0             30128.0
88639                            0                     0               587.0
77582                            0                     0              4139.0
119129                           0                     0              1735.0
54002                            0                     0              5357.0
110762                           0                     0              1698.0
57476                            0                     0             10150.0
173194                           0                     0               479.0

        Anno Censimento Superficie (Kmq)  Anno (Superficie)  \
178430             2021          19,5644               2024
147657             2011          28,6736               2020
14971              2001          37,4531               2002
88639              2011           7,1687               2012
77582              2011          18,5685               2011
119129             2011          98,6116               2016
54002              2001          11,9054               2008
110762             2011           8,9883               2015
57476              2001          29,3430               2008
173194             2021           5,9723               2024

        Popolazione residente  Anno (Popolazione residente)  Anno
178430                   1739                          2024  2024
147657                   7187                          2020  2020
14971                   29948                          2002  2002
88639                     551                          2012  2012
77582                    4165                          2011  2011
119129                   1640                          2016  2016
54002                    5646                          2008  2008
110762                   1638                          2015  2015
57476                   10087                          2008  2008
173194                    506                          2024  2024

From the previous cell we can see there are some nan values (about 2000) in the column "Sigla automobilistica".

In [8]:
print(situas_df[pd.isna(situas_df['Sigla automobilistica'])])
print(situas_df['Codice Regione'][pd.isna(situas_df['Sigla automobilistica'])].unique())

        Codice Ripartizione geografica  Codice Regione  Codice Provincia/Uts  \
4944                                 4              15                    63
4945                                 4              15                    63
4946                                 4              15                    63
4947                                 4              15                    63
4948                                 4              15                    63
...                                ...             ...                   ...
177255                               4              15                    63
177256                               4              15                    63
177257                               4              15                    63
177258                               4              15                    63
177259                               4              15                    63

        Codice Comune (alfanumerico)  Codice Comune (numerico)  \
4944                           63001                     63001
4945                           63002                     63002
4946                           63003                     63003
4947                           63004                     63004
4948                           63005                     63005
...                              ...                       ...
177255                         63088                     63088
177256                         63089                     63089
177257                         63090                     63090
177258                         63091                     63091
177259                         63092                     63092

                        Comune Sigla automobilistica  \
4944                    Acerra                   NaN
4945                  Afragola                   NaN
4946                   Agerola                   NaN
4947                  Anacapri                   NaN
4948                    Arzano                   NaN
...                        ...                   ...
177255                Visciano                   NaN
177256                   Volla                   NaN
177257  Santa Maria la CaritÃ                    NaN
177258                 Trecase                   NaN
177259          Massa di Somma                   NaN

        Capoluogo di Provincia/Uts  Capoluogo di Regione  Popolazione legale  \
4944                             0                     0             45688.0
4945                             0                     0             62319.0
4946                             0                     0              7348.0
4947                             0                     0              5855.0
4948                             0                     0             38510.0
...                            ...                   ...                 ...
177255                           0                     0              4199.0
177256                           0                     0             25369.0
177257                           0                     0             11689.0
177258                           0                     0              8594.0
177259                           0                     0              5056.0

        Anno Censimento Superficie (Kmq)  Anno (Superficie)  \
4944               2001          54,7117               2001
4945               2001          17,9117               2001
4946               2001          19,8315               2001
4947               2001           6,4666               2001
4948               2001           4,7062               2001
...                 ...              ...                ...
177255             2021          10,9035               2024
177256             2021           6,2162               2024
177257             2021           3,9788               2024
177258             2021           6,2619               2024
177259             2021           3,0420               2024

        Popolazione residente  Anno (Popolazione residente)  Anno
4944                    45912                          2001  2001
4945                    62315                          2001  2001
4946                     7351                          2001  2001
4947                     5859                          2001  2001
4948                    38499                          2001  2001
...                       ...                           ...   ...
177255                   4143                          2024  2024
177256                  25936                          2024  2024
177257                  11788                          2024  2024
177258                   8580                          2024  2024
177259                   4965                          2024  2024

[2208 rows x 16 columns]
[15]

Investigating on this columns, we can see that all nan values have "Codice Regione" $= 15$. This code stands for "Campania". We can fill these nan with the correct code using the column "Codice Provincia"

In [9]:
# we can discover the province code for each of the 5 province of Campania.
# Then we can fill nan values in column "Sigla automobilistica" with the correct string code.
province_code = []
province_name = []
for i in range(0,len(situas_df)):
    if situas_df['Comune'].iloc[i] in ['Napoli','Caserta','Salerno','Avellino','Benevento']:
        province_code.append(situas_df['Codice Provincia/Uts'].iloc[i])
        province_name.append(situas_df['Comune'].iloc[i])
province_campania_df = pd.DataFrame({'Codice Provincia/Uts': province_code, 'Nome Provincia/Uts': province_name})
print(province_campania_df)

for i in range(0,len(situas_df)):
    if pd.isna(situas_df['Sigla automobilistica'].iloc[i]):
        if situas_df['Codice Provincia/Uts'].iloc[i] == 61:
            situas_df.loc[i,'Sigla automobilistica'] = 'CE'
        elif situas_df['Codice Provincia/Uts'].iloc[i] == 62:
            situas_df.loc[i,'Sigla automobilistica'] = 'BN'
        elif situas_df['Codice Provincia/Uts'].iloc[i] == 63:
            situas_df.loc[i,'Sigla automobilistica']  = 'NA'
        elif situas_df['Codice Provincia/Uts'].iloc[i] == 64:
            situas_df.loc[i,'Sigla automobilistica'] = 'AV'
        elif situas_df['Codice Provincia/Uts'].iloc[i] == 65:
            situas_df.loc[i,'Sigla automobilistica'] = 'SA'

print(situas_df.info())
print(situas_df.sample(10))

     Codice Provincia/Uts Nome Provincia/Uts
0                      61            Caserta
1                      62          Benevento
2                      63             Napoli
3                      64           Avellino
4                      65            Salerno
..                    ...                ...
115                    61            Caserta
116                    62          Benevento
117                    63             Napoli
118                    64           Avellino
119                    65            Salerno

[120 rows x 2 columns]
<class 'pandas.DataFrame'>
RangeIndex: 179712 entries, 0 to 179711
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Codice Ripartizione geografica  179712 non-null  int64
 1   Codice Regione                  179712 non-null  int64
 2   Codice Provincia/Uts            179712 non-null  int64
 3   Codice Comune (alfanumerico)    179712 non-null  int64
 4   Codice Comune (numerico)        179712 non-null  int64
 5   Comune                          179688 non-null  str
 6   Sigla automobilistica           179712 non-null  str
 7   Capoluogo di Provincia/Uts      179712 non-null  int64
 8   Capoluogo di Regione            179712 non-null  int64
 9   Popolazione legale              179712 non-null  float64
 10  Anno Censimento                 179712 non-null  int64
 11  Superficie (Kmq)                179712 non-null  str
 12  Anno (Superficie)               179712 non-null  int64
 13  Popolazione residente           179712 non-null  int64
 14  Anno (Popolazione residente)    179712 non-null  int64
 15  Anno                            179712 non-null  int64
dtypes: float64(1), int64(12), str(3)
memory usage: 21.9 MB
None
        Codice Ripartizione geografica  Codice Regione  Codice Provincia/Uts  \
145401                               2               5                    26
110320                               4              13                    68
172722                               1               1                     4
128374                               1               2                     7
176382                               3               9                    49
148511                               4              18                    79
90322                                1               1                     3
69229                                1               3                    16
136943                               1               3                    17
116447                               3               9                    48

        Codice Comune (alfanumerico)  Codice Comune (numerico)  \
145401                         26007                     26007
110320                         68023                     68023
172722                          4024                      4024
128374                          7057                      7057
176382                         49017                     49017
148511                         79025                     79025
90322                           3143                      3143
69229                          16030                     16030
136943                         17112                     17112
116447                         48027                     48027

                       Comune Sigla automobilistica  \
145401      Cappella Maggiore                    TV
110320  Montebello di Bertona                    PE
172722              Borgomale                    CN
128374                 Roisan                    AO
176382    Rosignano Marittimo                    LI
148511              Centrache                    CZ
90322                    Suno                    NO
69229            Bonate Sopra                    BG
136943     Monticelli Brusati                    BS
116447              Montaione                    FI

        Capoluogo di Provincia/Uts  Capoluogo di Regione  Popolazione legale  \
145401                           0                     0              4677.0
110320                           0                     0              1023.0
172722                           0                     0               386.0
128374                           0                     0              1042.0
176382                           0                     0             30072.0
148511                           0                     0               415.0
90322                            0                     0              2808.0
69229                            0                     0              6238.0
136943                           0                     0              4401.0
116447                           0                     0              3776.0

        Anno Censimento Superficie (Kmq)  Anno (Superficie)  \
145401             2011          11,0891               2020
110320             2011          21,5012               2015
172722             2021           8,4778               2024
128374             2011          14,6410               2018
176382             2021         120,8274               2024
148511             2011           7,9582               2020
90322              2011          21,3271               2013
69229              2001           6,1510               2010
136943             2011          10,8908               2019
116447             2011         104,7585               2016

        Popolazione residente  Anno (Popolazione residente)  Anno
145401                   4651                          2020  2020
110320                    991                          2015  2015
172722                    368                          2024  2024
128374                   1023                          2018  2018
176382                  30095                          2024  2024
148511                    360                          2020  2020
90322                    2815                          2013  2013
69229                    8826                          2010  2010
136943                   4533                          2019  2019
116447                   3686                          2016  2016

In [ ]:
# Save situas dataframe to csv file in data clean folder
situas_df.to_csv("data/clean/situas_df.csv", index=False, sep = ";", decimal = ",")

Now, we can move to clean `ISTAT data` csv file

In [11]:
istat_df = pd.read_csv("data/raw/istat_incidenti.csv")
print(istat_df.info())
print(istat_df.sample(10))

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  int64
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(3), str(4)
memory usage: 70.0 MB
None
               DATAFLOW FREQ  REF_AREA DATA_TYPE RESULT  TIME_PERIOD  \
105222  IT1:41_983(1.0)    A     12130   ROADACC      9         2010
245153  IT1:41_983(1.0)    A     27038   ROADACC      9         2006
278809  IT1:41_983(1.0)    A     36006   KILLINJ      M         2017
567566  IT1:41_983(1.0)    A    108028   KILLINJ      F         2021
305120  IT1:41_983(1.0)    A     44044   KILLINJ      F         2012
419670  IT1:41_983(1.0)    A     69091   KILLINJ      F         2004
411311  IT1:41_983(1.0)    A     68018   ROADACC      9         2024
240494  IT1:41_983(1.0)    A     26069   KILLINJ      F         2021
180479  IT1:41_983(1.0)    A     19015   KILLINJ      M         2024
305413  IT1:41_983(1.0)    A     44052   KILLINJ      F         2002

        OBS_VALUE  OBS_STATUS  NOTE_DS  NOTE_REF_AREA  NOTE_DATA_TYPE  \
105222         44         NaN      NaN            NaN             NaN
245153         42         NaN      NaN            NaN             NaN
278809          2         NaN      NaN            NaN             NaN
567566        180         NaN      NaN            NaN             NaN
305120          2         NaN      NaN            NaN             NaN
419670         26         NaN      NaN            NaN             NaN
411311          4         NaN      NaN            NaN             NaN
240494         54         NaN      NaN            NaN             NaN
180479          0         NaN      NaN            NaN             NaN
305413          1         NaN      NaN            NaN             NaN

        NOTE_RESULT  NOTE_TIME_PERIOD  BASE_PER  UNIT_MEAS  UNIT_MULT
105222          NaN               NaN       NaN        NaN        NaN
245153          NaN               NaN       NaN        NaN        NaN
278809          NaN               NaN       NaN        NaN        NaN
567566          NaN               NaN       NaN        NaN        NaN
305120          NaN               NaN       NaN        NaN        NaN
419670          NaN               NaN       NaN        NaN        NaN
411311          NaN               NaN       NaN        NaN        NaN
240494          NaN               NaN       NaN        NaN        NaN
180479          NaN               NaN       NaN        NaN        NaN
305413          NaN               NaN       NaN        NaN        NaN

Since the columns from "OBS_STATUS" to "UNIT_MULT" contain only nan values, and these columns are meant to contain only optional data like metadata or notes, we can drop them

In [12]:
# we cycle over all columns of the istat_df dataframe and check if there are any missing values. 
# If there are, we drop the column.
for i in istat_df.columns:
    if pd.isna(istat_df[i]).sum() > 0:
        print(f"Column {i} has {pd.isna(istat_df[i]).sum()} missing values")
        istat_df.drop(columns=[i],inplace=True)
print(istat_df.info())
print(istat_df.sample(10))

Column OBS_STATUS has 573552 missing values
Column NOTE_DS has 573552 missing values
Column NOTE_REF_AREA has 573552 missing values
Column NOTE_DATA_TYPE has 573552 missing values
Column NOTE_RESULT has 573552 missing values
Column NOTE_TIME_PERIOD has 573552 missing values
Column BASE_PER has 573552 missing values
Column UNIT_MEAS has 573552 missing values
Column UNIT_MULT has 573552 missing values
<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATAFLOW     573552 non-null  str
 1   FREQ         573552 non-null  str
 2   REF_AREA     573552 non-null  int64
 3   DATA_TYPE    573552 non-null  str
 4   RESULT       573552 non-null  str
 5   TIME_PERIOD  573552 non-null  int64
 6   OBS_VALUE    573552 non-null  int64
dtypes: int64(3), str(4)
memory usage: 30.6 MB
None
               DATAFLOW FREQ  REF_AREA DATA_TYPE RESULT  TIME_PERIOD  \
108612  IT1:41_983(1.0)    A     13050   ROADACC      9         2006
3868    IT1:41_983(1.0)    A      1055   KILLINJ      M         2014
540432  IT1:41_983(1.0)    A     97016   ROADACC      9         2007
528647  IT1:41_983(1.0)    A     95015   KILLINJ      M         2013
520638  IT1:41_983(1.0)    A     93005   ROADACC      9         2019
52329   IT1:41_983(1.0)    A      4250   ROADACC      9         2001
338829  IT1:41_983(1.0)    A     57027   KILLINJ      F         2022
42001   IT1:41_983(1.0)    A      4104   KILLINJ      M         2011
291205  IT1:41_983(1.0)    A     41001   ROADACC      9         2017
132273  IT1:41_983(1.0)    A     15216   ROADACC      9         2004

        OBS_VALUE
108612          0
3868            0
540432         18
528647          0
520638         36
52329           3
338829         40
42001           0
291205         12
132273         19

In [13]:
# with the following lines of code we can check 
# the unique content of every column to understand what they mean
print(istat_df['DATAFLOW'].unique())
print(istat_df['FREQ'].unique())
print(istat_df['TIME_PERIOD'].unique())
print(istat_df['DATA_TYPE'].unique())
print(istat_df['RESULT'].unique())

<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str
<StringArray>
['A']
Length: 1, dtype: str
[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]
<StringArray>
['KILLINJ', 'ROADACC']
Length: 2, dtype: str
<StringArray>
['F', 'M', '9']
Length: 3, dtype: str

From the output we can notice that it's necessary to investigate further on the meaning of each variable

After doing some online research at the following links:

https://esploradati.istat.it/SDMXWS/rest/datastructure/IT1/DCIS_INCIDMORFER_COM/
https://esploradati.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO22
https://esploradati.istat.it/SDMXWS/rest/codelist/IT1/CL_ESITO
https://esploradati.istat.it/SDMXWS/rest/conceptscheme/IT1/CROSS_DOMAIN

you can understand the meaning of each variable. First, it is clear that each row represents a single observation, whose value is identified by the “OBS_VALUE” column, which is labeled by various categorical dimensions identified by the columns: “DATA_TYPE” and “RESULT,” which have the labels KILLINJ/ROADACC and F/M/9, respectively (F stands for injured, M for fatality, and 9 is the label for “total,” i.e., the total number of accidents that occurred in a given municipality over the course of a year).
So, for example, if you have a record with a structure like this:\

REF_AREA = 001001\
DATA_TYPE = ROADACC\
RESULT = 9\
TIME_PERIOD = 2001\
OBS_VALUE = 10\

this means that in the town with code 001001, a total of 10 traffic accidents occurred in 2001

Given the structure of the data frame, it is advisable to apply a pivot transformation to create columns showing the actual number of injuries, deaths, and accidents for each town and for each year. This will facilitate the linking of the ISTAT data with the SITUAS data.

In [14]:
# pivot trasformation
istat_tmp_df = istat_df.pivot_table(index = ['REF_AREA','TIME_PERIOD'], columns = ['DATA_TYPE','RESULT'], values = 'OBS_VALUE').reset_index()

# Rename columns to more meaningful names
istat_tmp_df.columns = ['Ref_Area','Time_Period','N_Injured','N_Dead','N_Accidents']

# Insert "Dataflow" and "Frequency" columns lost in the pivoting operation
istat_tmp_df.insert(0, 'Dataflow', istat_df['DATAFLOW'])
istat_tmp_df.insert(1, 'Frequency', istat_df['FREQ'])
istat_df = istat_tmp_df

# Convert numeric columns to int
istat_df['N_Injured'] = istat_df['N_Injured'].astype(int)
istat_df['N_Dead'] = istat_df['N_Dead'].astype(int)
istat_df['N_Accidents'] = istat_df['N_Accidents'].astype(int)
istat_df.head(10)

,Dataflow,Frequency,Ref_Area,Time_Period,N_Injured,N_Dead,N_Accidents
0,IT1:41_983(1.0),A,1001,2001,10,0,5
1,IT1:41_983(1.0),A,1001,2002,10,0,5
2,IT1:41_983(1.0),A,1001,2003,7,0,4
3,IT1:41_983(1.0),A,1001,2004,13,0,9
4,IT1:41_983(1.0),A,1001,2005,2,0,2
5,IT1:41_983(1.0),A,1001,2006,1,0,1
6,IT1:41_983(1.0),A,1001,2007,12,0,8
7,IT1:41_983(1.0),A,1001,2008,10,0,5
8,IT1:41_983(1.0),A,1001,2009,7,0,4
9,IT1:41_983(1.0),A,1001,2010,14,0,7

In [15]:
# after the pivoting of the table, we can check if there are any missing values
print(istat_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 191184 entries, 0 to 191183
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Dataflow     191184 non-null  str
 1   Frequency    191184 non-null  str
 2   Ref_Area     191184 non-null  int64
 3   Time_Period  191184 non-null  int64
 4   N_Injured    191184 non-null  int64
 5   N_Dead       191184 non-null  int64
 6   N_Accidents  191184 non-null  int64
dtypes: int64(5), str(2)
memory usage: 10.2 MB
None

There are no missing values left. We can save the dataframe in a csv file

In [16]:
# Save istat dataframe to csv file in data clean folder
istat_df.to_csv("data/clean/istat_df.csv", index=False)

Now, we can join the dataframes (situas and istat) into a bigger and enriched dataframe containing information about car accidents that happened in each town in Italy each year from 2001 to 2024 (istat data). Moreover, this dataframe will have information about towns, such as their population and their surface area (situas data)

In [17]:
merged_df = pd.merge(istat_df, situas_df, left_on = ['Ref_Area','Time_Period'], right_on = ['Codice Comune (alfanumerico)','Anno'], how = 'inner')
print(merged_df.info())
print(merged_df.sample(10))

<class 'pandas.DataFrame'>
RangeIndex: 178209 entries, 0 to 178208
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Dataflow                        178209 non-null  str
 1   Frequency                       178209 non-null  str
 2   Ref_Area                        178209 non-null  int64
 3   Time_Period                     178209 non-null  int64
 4   N_Injured                       178209 non-null  int64
 5   N_Dead                          178209 non-null  int64
 6   N_Accidents                     178209 non-null  int64
 7   Codice Ripartizione geografica  178209 non-null  int64
 8   Codice Regione                  178209 non-null  int64
 9   Codice Provincia/Uts            178209 non-null  int64
 10  Codice Comune (alfanumerico)    178209 non-null  int64
 11  Codice Comune (numerico)        178209 non-null  int64
 12  Comune                          178185 non-null  str
 13  Sigla automobilistica           178209 non-null  str
 14  Capoluogo di Provincia/Uts      178209 non-null  int64
 15  Capoluogo di Regione            178209 non-null  int64
 16  Popolazione legale              178209 non-null  float64
 17  Anno Censimento                 178209 non-null  int64
 18  Superficie (Kmq)                178209 non-null  str
 19  Anno (Superficie)               178209 non-null  int64
 20  Popolazione residente           178209 non-null  int64
 21  Anno (Popolazione residente)    178209 non-null  int64
 22  Anno                            178209 non-null  int64
dtypes: float64(1), int64(17), str(5)
memory usage: 31.3 MB
None
               Dataflow Frequency  Ref_Area  Time_Period  N_Injured  N_Dead  \
69150   IT1:41_983(1.0)         A     23046         2020          0       0
24157   IT1:41_983(1.0)         A      6190         2007          1       0
66478   IT1:41_983(1.0)         A     22117         2023         29       0
171616  IT1:41_983(1.0)         A     97035         2019          1       0
65174   IT1:41_983(1.0)         A     22033         2003          6       0
139086  IT1:41_983(1.0)         A     74011         2001         45       3
40183   IT1:41_983(1.0)         A     15036         2021         72       2
102969  IT1:41_983(1.0)         A     54030         2021         14       0
88178   IT1:41_983(1.0)         A     36008         2024         62       1
4193    IT1:41_983(1.0)         A      1180         2018          1       0

        N_Accidents  Codice Ripartizione geografica  Codice Regione  \
69150             0                               2               5
24157             1                               1               1
66478            19                               2               4
171616            1                               1               3
65174             3                               2               4
139086           23                               4              16
40183            61                               1               3
102969           11                               3              10
88178            45                               2               8
4193              1                               1               1

        Codice Provincia/Uts  ...  Sigla automobilistica  \
69150                     23  ...                     VR
24157                      6  ...                     AL
66478                     22  ...                     TN
171616                    97  ...                     LC
65174                     22  ...                     TN
139086                    74  ...                     BR
40183                     15  ...                     MI
102969                    54  ...                     PG
88178                     36  ...                     MO
4193                       1  ...                     TO

        Capoluogo di Provincia/Uts Capoluogo di Regione Popolazione legale  \
69150                            0                    0             3083.0
24157                            0                    0              770.0
66478                            0                    0             7445.0
171616                           0                    0              750.0
65174                            0                    0             1040.0
139086                           0                    0            15209.0
40183                            0                    0            26912.0
102969                           0                    0             5421.0
88178                            0                    0            11158.0
4193                             0                    0             1119.0

        Anno Censimento  Superficie (Kmq)  Anno (Superficie)  \
69150              2011           18,6220               2020
24157              2001           52,1827               2007
66478              2021           13,8790               2023
171616             2011           18,0526               2019
65174              2001           20,8087               2003
139086             2001           83,6670               2001
40183              2021           12,0057               2021
102969             2021           69,5123               2021
88178              2021           49,7830               2024
4193               2011            4,4056               2018

        Popolazione residente Anno (Popolazione residente)  Anno
69150                    3122                         2020  2020
24157                     746                         2007  2007
66478                    7647                         2023  2023
171616                    757                         2019  2019
65174                    1044                         2003  2003
139086                  15176                         2001  2001
40183                   26912                         2021  2021
102969                   5421                         2021  2021
88178                   11052                         2024  2024
4193                     1113                         2018  2018

[10 rows x 23 columns]

From merged_df.info() we notice some errors that has to be handled:
1. "Comune" column has some null values. We can check why there are these null and decide to keep them as is, drop or fill them.
2. "Superficie (Kmq)" datatype is string and not int or float. We have to convert it in order to create other columns useful for the analysis.
3. There are redondant columns such as "Ref_Area" - "Codice Comune (alfanumerico)" - "Codice Comune (numerico)" and "Time Period" - "Anno". We can keep just one for year and one for town code.

In [23]:
# check towns code of towns that have null values in the "Comune" column after the merge operation.
merged_df[merged_df['Comune'].isnull()]

,Dataflow,Frequency,Ref_Area,Time_Period,N_Injured,N_Dead,N_Accidents,Codice Ripartizione geografica,Codice Regione,Codice Provincia/Uts,...,Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente),Anno
3892,IT1:41_983(1.0),A,1168,2001,23,0,13,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2001,7749,2001,2001
3893,IT1:41_983(1.0),A,1168,2002,46,1,20,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2002,7777,2002,2002
3894,IT1:41_983(1.0),A,1168,2003,25,4,16,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2003,7822,2003,2003
3895,IT1:41_983(1.0),A,1168,2004,29,0,15,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2004,7838,2004,2004
3896,IT1:41_983(1.0),A,1168,2005,20,3,14,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2005,7815,2005,2005
3897,IT1:41_983(1.0),A,1168,2006,32,1,20,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2006,7798,2006,2006
3898,IT1:41_983(1.0),A,1168,2007,11,0,7,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2007,7866,2007,2007
3899,IT1:41_983(1.0),A,1168,2008,42,0,19,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2008,7873,2008,2008
3900,IT1:41_983(1.0),A,1168,2009,14,0,8,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2009,7859,2009,2009
3901,IT1:41_983(1.0),A,1168,2010,8,0,6,1,1,1,...,TO,0,0,7761.0,2001,"24,6422",2010,7986,2010,2010
3902,IT1:41_983(1.0),A,1168,2011,13,0,11,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2011,8063,2011,2011
3903,IT1:41_983(1.0),A,1168,2012,13,0,11,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2012,8038,2012,2012
3904,IT1:41_983(1.0),A,1168,2013,9,0,9,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2013,8063,2013,2013
3905,IT1:41_983(1.0),A,1168,2014,15,0,13,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2014,8077,2014,2014
3906,IT1:41_983(1.0),A,1168,2015,14,2,11,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2015,8019,2015,2015
3907,IT1:41_983(1.0),A,1168,2016,14,1,11,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2016,8029,2016,2016
3908,IT1:41_983(1.0),A,1168,2017,25,2,16,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2017,8039,2017,2017
3909,IT1:41_983(1.0),A,1168,2018,14,0,7,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2018,8055,2018,2018
3910,IT1:41_983(1.0),A,1168,2019,11,0,9,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2019,7969,2019,2019
3911,IT1:41_983(1.0),A,1168,2020,11,0,8,1,1,1,...,TO,0,0,7998.0,2011,"24,6422",2020,7849,2020,2020
3912,IT1:41_983(1.0),A,1168,2021,11,0,9,1,1,1,...,TO,0,0,7830.0,2021,"24,6422",2021,7830,2021,2021
3913,IT1:41_983(1.0),A,1168,2022,10,0,7,1,1,1,...,TO,0,0,7830.0,2021,"24,6422",2022,7790,2022,2022
3914,IT1:41_983(1.0),A,1168,2023,9,0,7,1,1,1,...,TO,0,0,7830.0,2021,"24,6422",2023,7688,2023,2023
3915,IT1:41_983(1.0),A,1168,2024,7,0,5,1,1,1,...,TO,0,0,7830.0,2021,"24,6422",2024,7662,2024,2024

From the previous cell output it can be noticed that just one town has null values in the column "Comune" in the dataset. Since that we know only province and state of this town, it's not possibile to reveal its name. Moreover, null values are very few (24 vs ~170.000) so we can drop these records.

In [ ]:
# drop rows with null values in the "Comune" column and reset the index of the dataframe
merged_df.drop(merged_df[merged_df['Comune'].isnull()].index, inplace=True)
merged_df.reset_index(inplace=True, drop=True)
print(merged_df.info())
print(merged_df.sample(10))

<class 'pandas.DataFrame'>
RangeIndex: 178185 entries, 0 to 178184
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Dataflow                        178185 non-null  str
 1   Frequency                       178185 non-null  str
 2   Ref_Area                        178185 non-null  int64
 3   Time_Period                     178185 non-null  int64
 4   N_Injured                       178185 non-null  int64
 5   N_Dead                          178185 non-null  int64
 6   N_Accidents                     178185 non-null  int64
 7   Codice Ripartizione geografica  178185 non-null  int64
 8   Codice Regione                  178185 non-null  int64
 9   Codice Provincia/Uts            178185 non-null  int64
 10  Codice Comune (alfanumerico)    178185 non-null  int64
 11  Codice Comune (numerico)        178185 non-null  int64
 12  Comune                          178185 non-null  str
 13  Sigla automobilistica           178185 non-null  str
 14  Capoluogo di Provincia/Uts      178185 non-null  int64
 15  Capoluogo di Regione            178185 non-null  int64
 16  Popolazione legale              178185 non-null  float64
 17  Anno Censimento                 178185 non-null  int64
 18  Superficie (Kmq)                178185 non-null  str
 19  Anno (Superficie)               178185 non-null  int64
 20  Popolazione residente           178185 non-null  int64
 21  Anno (Popolazione residente)    178185 non-null  int64
 22  Anno                            178185 non-null  int64
dtypes: float64(1), int64(17), str(5)
memory usage: 31.3 MB
None
               Dataflow Frequency  Ref_Area  Time_Period  N_Injured  N_Dead  \
111347  IT1:41_983(1.0)         A     60004         2018          3       0
46790   IT1:41_983(1.0)         A     16171         2008          2       0
9497    IT1:41_983(1.0)         A      3025         2005         39       0
164377  IT1:41_983(1.0)         A     91090         2022          0       0
52146   IT1:41_983(1.0)         A     17149         2015         30       0
136249  IT1:41_983(1.0)         A     71024         2012       1021      17
162747  IT1:41_983(1.0)         A     90060         2013          0       0
131293  IT1:41_983(1.0)         A     69002         2002          5       0
153258  IT1:41_983(1.0)         A     82013         2015         14       0
118125  IT1:41_983(1.0)         A     63016         2018         43       0

        N_Accidents  Codice Ripartizione geografica  Codice Regione  \
111347            3                               3              12
46790             2                               1               3
9497             27                               1               1
164377            0                               5              20
52146            17                               1               3
136249          572                               4              16
162747            0                               5              20
131293            4                               4              13
153258            8                               5              19
118125           26                               4              15

        Codice Provincia/Uts  ...  Sigla automobilistica  \
111347                    60  ...                     FR
46790                     16  ...                     BG
9497                       3  ...                     NO
164377                    91  ...                     NU
52146                     17  ...                     BS
136249                    71  ...                     FG
162747                    90  ...                     SS
131293                    69  ...                     CH
153258                    82  ...                     PA
118125                    63  ...                     NA

        Capoluogo di Provincia/Uts Capoluogo di Regione Popolazione legale  \
111347                           0                    0             2852.0
46790                            0                    0             2934.0
9497                             0                    0             3853.0
164377                           0                    0              610.0
52146                            0                    0             7121.0
136249                           1                    0           147036.0
162747                           0                    0              757.0
131293                           0                    0             2336.0
153258                           0                    0             7021.0
118125                           0                    0            22322.0

        Anno Censimento  Superficie (Kmq)  Anno (Superficie)  \
111347             2011           51,7134               2018
46790              2001           10,3776               2008
9497               2001           13,3928               2005
164377             2021           43,8005               2022
52146              2011           29,2070               2015
136249             2011          509,2545               2012
162747             2011           53,1002               2013
131293             2001           28,5443               2002
153258             2011           26,0237               2015
118125             2011            3,1983               2018

        Popolazione residente Anno (Popolazione residente)  Anno
111347                   2606                         2018  2018
46790                    3243                         2008  2008
9497                     4388                         2005  2005
164377                    595                         2022  2022
52146                    7021                         2015  2015
136249                 151990                         2012  2012
162747                    748                         2013  2013
131293                   2334                         2002  2002
153258                   7430                         2015  2015
118125                  22035                         2018  2018

[10 rows x 23 columns]